repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-encoding-pragma
        args: ["--remove"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        # TODO: Figure out how to use the same dependencies we have
        # in the requirements.txt file.
        additional_dependencies: [
          types-pyyaml==6.0.12,
          types-redis==4.6.0,
          types-requests==2.31.0,
          types-tabulate==0.9.0,
          types-paramiko==3.4.0.20240423,
          types-setuptools==71.1.0.20240723,
        ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
        exclude: ^.*\/(k8s_.*_ops\.py|regionsilo_.*\.py)
      # Run the formatter.
      - id: ruff-format
        exclude: ^.*\/(k8s_.*_ops\.py|regionsilo_.*\.py)
