name: build

on:
  push:
    branches:
      - release/**
  pull_request:

jobs:
  dist:
    name: Create wheel
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: |
          pip install wheel
          python setup.py bdist_wheel
      - uses: actions/upload-artifact@v3.1.1
        if: github.event_name != 'pull_request'
        with:
          name: ${{ github.sha }}
          path: dist/*
